#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html
#
# Experiment: E3SM ensembles only (no CMIP6).

#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q regular
#SBATCH -J ilamb-e3sm-only
#SBATCH --mail-user=sfeng@pnnl.gov
#SBATCH --mail-type=ALL
#SBATCH -A e3sm
#SBATCH -t 1:00:0
#SBATCH --ntasks=9
#SBATCH --cpus-per-task=14

set -eo pipefail

readonly RUN_TASKS=9
readonly BUILD_DIR=/global/cfs/cdirs/e3sm/www/sfeng/v3.XLE/_build_e3sm_only

# OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

# ILAMB setup:
export ILAMB_ROOT=/global/cfs/cdirs/e3sm/feng809/v3.XLE/ilamb
ln -sfn /global/cfs/cdirs/e3sm/feng809/data/ILAMB-DATA "${ILAMB_ROOT}/DATA"
source /global/cfs/cdirs/e3sm/feng809/code/miniconda3/bin/activate ilamb
set -u
mkdir -p "${BUILD_DIR}"

# The conda environment contains Intel MPI. Verify that Hydra's Slurm
# bootstrap created one shared communicator before ILAMB writes shared files.
export ILAMB_EXPECTED_MPI_SIZE="${RUN_TASKS}"
if ! mpiexec -bootstrap slurm -n "${RUN_TASKS}" python -c \
  'from mpi4py import MPI; import os; assert MPI.COMM_WORLD.size == int(os.environ["ILAMB_EXPECTED_MPI_SIZE"])'; then
  echo "ERROR: MPI launcher did not create a ${RUN_TASKS}-rank communicator" >&2
  exit 1
fi

# Run the application.
cd "${ILAMB_ROOT}"
mpiexec -bootstrap slurm -n "${RUN_TASKS}" ilamb-run \
     --config ilamb.cfg \
     --model_setup models_e3sm_only.yaml \
     --define_regions "${ILAMB_ROOT}/DATA/regions/GlobalLand.nc" "${ILAMB_ROOT}/DATA/regions/LandRegions.nc" "${ILAMB_ROOT}/regions.txt" \
     --regions global southamericaamazon eqas eqaf hilat temperate \
     --study_limits 1985 2014 \
     --rmse_score_basis cycle \
     --title "v3.XLE E3SM ensembles historical" \
     --build_dir "${BUILD_DIR}"
